//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQ2GlassCannon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQ2GlassCannon.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Innoruuk&apos;s Child&quot;,false,false,false,0,0.8,0,1
        ///&quot;Crystallized Essence (Master)&quot;,false,false,false,0,0.8,0,1
        ///&quot;Crystallized Essence (Expert)&quot;,false,false,false,0,0.8,0,1
        ///&quot;Crystal Gift&quot;,false,false,false,0.5,1,0,0.8
        ///&quot;Overflowing Vessel of Fyr&apos;Un&quot;,true,false,false,0.5,1,0,0.8
        ///&quot;Manastone&quot;,false,false,false,0.5,1,0,0.8
        ///&quot;Shard of Essence (Master)&quot;,false,false,false,0.5,1,0,0.8
        ///&quot;Shard of Essence (Expert)&quot;,false,false,false,0.5,1,0,0.8
        ///&quot;Dark Heart (Master)&quot;,false,false,false,0.5,1,0,0.8
        ///&quot;Dark Heart (Expert)&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomRegenItemsTextFile {
            get {
                return ResourceManager.GetString("CustomRegenItemsTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;!&quot;, &quot;assist me&quot;, &quot;/gc_attackassist {0}&quot;
        ///&quot;!&quot;, &quot;come&quot;, &quot;/gc_stance follow&quot;
        ///&quot;!&quot;, &quot;stay close&quot;, &quot;/gc_stance customfollow&quot;
        ///&quot;!&quot;, &quot;shadow me&quot;, &quot;/gc_stance shadow&quot;
        ///&quot;!&quot;, &quot;stay here&quot;, &quot;/gc_stance stay&quot;
        ///&quot;!&quot;, &quot;dash forward&quot;, &quot;/gc_stance dash&quot;
        ///&quot;!&quot;, &quot;stop dps&quot;, &quot;/gc_exit&quot;
        ///&quot;!&quot;, &quot;beddy-bye!!&quot;, &quot;/gc_exitprocess&quot;
        ///&quot;!&quot;, &quot;afk&quot;, &quot;/gc_stance afk&quot;
        ///&quot;!&quot;, &quot;neutral&quot;, &quot;/gc_stance neutral&quot;
        ///&quot;!&quot;, &quot;rebuff me pls&quot;, &quot;/gc_reloadsettings&quot;
        ///&quot;!&quot;, &quot;redo group buffs&quot;, &quot;/gc_cancelgroupbuffs&quot;
        ///&quot;!&quot;, &quot;sanctuary&quot;, &quot;/cancel_spellcast&quot;, &quot;/usea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomTriggersTextFile {
            get {
                return ResourceManager.GetString("CustomTriggersTextFile", resourceCulture);
            }
        }
    }
}
